### ISSUE TITLE
php-fpm

### ISSUE THREAD

**Issue by the-stardust** [ruesin/php-tree#1]
在nginx分类里面的php-fpm里面有写到 master会接收来自web的请求，然后选择一个worker进行处理，但是真实的场景好像是master创建worker后，master只会进行对worker的一些管理(kill and created)和加载配置文件等等，而worker会accept去接收请求，与文中说的master转发请求给worker，这样子是不是有问题，如果这样的话，所有请求都过master一遍，那么master会成为瓶颈，在高并发场景下，并没有体现出来worker的多进程这种优势吧 QAQ

**Comment by ruesin** [comment]
[纠正错误](https://github.com/ruesin/php-tree/commit/55c61058bd8e9481f51ccfb42ed3f002c57345e5#diff-e36055e6b3079484b0890b522d3d2e3f6658926ed14b0ebbaa52ede74911b7dc)

多谢指正，记录得有点糙~  

:-)
